server:
  port: 5555
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: "select 1"
      minimum-idle: 1
      maximum-pool-size: 2
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 180000
    initialization-mode: always
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default-schema: public
        format-sql: true
        show-sql: true
    hibernate:
      ddl-auto: create-drop
