server:
  port: 5555
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: "select 1"
      minimum-idle: 1
      maximum-pool-size: 2
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 180000
    initialization-mode: always
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default-schema: public
        format-sql: true
        show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          ssl:
            enable: true
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2
      max-file-size: 200MB
      max-request-size: 215MB
security:
  jwt:
    token:
      secret-key: "Chave secreta para ser utilizada na api"
      expire-length: 3600000000
default:
  sender: weskleypedro@gmail.com
  dns: http://localhost:5555
  front-url: http://localhost:8080